### ISSUE TITLE
removing pcre breaks things

### ISSUE THREAD

**Issue by grooveuser** [goodtiding5/docker-nitter#4]
In commit dc54ece to Dockerfile  'unnecessary packages were removed.'

[dc54ece](https://github.com/goodtiding5/docker-nitter/commit/dc54ece5c4d16271083e5c31e8edea36be04dece#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557)

I think removing pcre broke this for me.

When starting I get:
`nitter_1 | could not load: libpcre.so(.3|.1|)
`
rolling back to the 20210614 image works. 
I'm about to rebuild from the Dockerfile to make sure that's the issue. (yes, I've been lazy)

BTW, thanks!

**Comment by goodtiding5** [comment]
Thanks for the notice.  It's a mistake and I just fixed it.
