### ISSUE TITLE
No videoplayback

### ISSUE THREAD

**Issue by Happyfeet01** [goodtiding5/docker-nitter#5]
Hello,

I use your image. Thanks for that. 
But I can't play any video. can you help me.?

My instance https://nitter.dasnetzundich.de

**Comment by goodtiding5** [comment]
Please check your nitter.conf file?  Make sure you are using a working invidious service.

Here is the one from nitter repo:

[Preferences]
... 
replaceYouTube = "piped.kavin.rocks"
